### PR TITLE
Fix header/footer `@IBInspectable` support

### PR DESCRIPTION
**Pull request by vtourraine**
As reported by #76

### CODE REVIEW

**Comment by iDevelopper** [comment]
I think you need to change the initializer code as well. Try to change the background color of the table view in the storyboard, for example.

```swift
    public required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
```

**Comment by vtourraine** [comment]
@iDevelopper Thanks for the feedback, I’ll keep working on it.

**Comment by vtourraine** [comment]
I fixed the initializer as you suggested, and updated the Manual Example project. I think the correct approach is to add a `UITableViewController` object in Interface Builder and set it as a `AcknowListViewController`. Then you get the table view properties in the inspector, so you can change not just the background color but also the table view style.

**Comment by iDevelopper** [comment]
Yes that's it ! Background color was an example. Great!

**Comment by iDevelopper** [comment]
When do you expect to make all these changes (VIP) on cocoapods?

**Comment by vtourraine** [comment]
My goal is to release that as a version 2.0, which is a great to allow ourselves to break things and make them better, but at the same time we want to be extra cautious.

So I’m not sure about the timeframe. I think we’re almost done, but I also want to give enough time so that other people have a chance to test this new version.

Let’s say I hope we can release it sometimes next month.

**Comment by iDevelopper** [comment]
Hello Vincent,

What about a better example. I wrote one in my pull request #71.

What do you think?

**Comment by vtourraine** [comment]
Your example is definitely more comprehensive. Though, to be honest, I’m not sure how useful it is, compared to the current version which already covers all the main configurations. Adding complexity to the example project implies a maintenance cost, so there has to be a meaningful added-value.

If you really find it useful, you can open a dedicated pull request. I’d be interested to know what other people think of this.

**Pull request merged**
