### PR TITLE
Make @IBInspectable variables public

### PR DESCRIPTION
**Pull request by BasThomas**
They can be set directly from code, now.

### CODE REVIEW

**Comment by vtourraine** [comment]
I'm really sorry about this super-late reply, but thanks for the pull request!

It makes total sense to have `public` header and footer properties. I'm not so sure about `acknowledgementsPlistName`, though, because if you load the acknowledgements programmatically, you should use the initializers instead.

**Comment by BasThomas** [comment]
Better late than never! ☺️
I think you are right about the `acknowledgementsPlistName` though; it doesn't make sense to set this later. Should I make another PR?

**Comment by BasThomas** [comment]
Also, if you can update the version number of the `pod` afterwards, that'd be great!

**Comment by vtourraine** [comment]
If you have 2 more minutes to spare, go head. Otherwise I'll edit it.

**Comment by vtourraine** [comment]
I was waiting for the Xcode 8 official release to push a new version, but it might be useful to push a new minor version **before**, for people who keep using Xcode 7 for now.

**Comment by BasThomas** [comment]
Yeah, a minor version update to fix this would be great.

**Comment by vtourraine** [comment]
There you go. I've reverted the change on `acknowledgementsPlistName`, and pushed version 1.0.1. 

Thanks once again for the pull request. 👍

**Pull request merged**
