### PR TITLE
Show only specified license types

### PR DESCRIPTION
**Pull request by naoty**
I added a feature which adds license types to acknowledgements.plist to CocoaPods (https://github.com/CocoaPods/CocoaPods/pull/5436). From 1.1.0.beta.1, the license type of each acknowledgements can be used. So, I want to filter acknowledgements by using this feature.

### CODE REVIEW

**Comment by vtourraine** [comment]
Sorry about this late reply, and thanks for sending the pull request!

This new "type" property is very interesting, so we should definitely update the `Acknow` class to handle it.

At the same time, I want to keep the general interface for this pod as straightforward as possible, and I think that filtering acknowledgements by type is a very specific use case. Could you revert the changes on the `AcknowListViewController` initializers? Once this pod supports the `type` property, everyone will be able to filter/combine/edit the acknowledgements accordingly in their own code. What do you think?

**Comment by naoty** [comment]
@vtourraine Thank you for reply. I'm sorry for late reply, too. I'm totally agree with your idea. I will remove `AcknowListViewController` initializers.

I use this library in Swift 2.3. Which branch should I send this pull request?

**Comment by vtourraine** [comment]
Great, thanks for the follow-up! 👍 

I’ve added a new `swift-2-3` branch, you can send your pull request there. Feel free to send another pull request for Swift 3 to `master`, otherwise I’ll just migrate it myself, to make it available to everyone going forward.

**Comment by naoty** [comment]
@vtourraine I changed the base branch to `swift-2.3` and reverted `AcknowListViewController` initializers.

**Comment by vtourraine** [comment]
Thanks so much for the update, I’m merging it in right now. 👍

**Comment by vtourraine** [comment]
I’ve now also ported these changes for Swift 3 on `master` (code is basically the same): cc04b7ffb9581db40eab2e18d8b9f56f738f30d4

**Comment by naoty** [comment]
@vtourraine Thank you for merging!

**Pull request merged**
